language: python
python:
- '2.7'
install:
- pip install tox coverage
script:
- tox
after_success:
- bash <(curl -s https://codecov.io/bash) -f '!./tests/*'
deploy:
  # test pypi
  - provider: pypi
    server: https://testpypi.python.org/pypi
    user: gdyuldin
    password:
      secure: "EhjyFBvlANx9Qe2cfu+BhoeA+DtVQhry+7VUkh0AUNOtLD2lXYOeKWWveaSQIeWibHEyCIyRiHVVf0eyxZ7VZFToScHFrGy1ck3k4uo5ZWeyg61dBkpBjb8xb3VFUbjzUmAc8z7RgoAPm2wyuo75/k03ty0lm+wDTZTc91e8ldC5VAsVkeVKA/8iSIr67YASJVm1pL+e5lWLvdgKO6rk5ATAjrzXUgrcG6s4HuukZ9qveVLvs1N1PQs44edWXu7tjKw/9/9iPM+4pyyQuE+z5aRai0CH0EDnH9BKEx7UyglAjIs3nUa4OvGDOWk/4QmUfZDTR0SiJi6SX1+t3dh/5LRLov9LEPDqLkuTm6OdzZcPvXXMwuJMmrHcXgwSGEp5VQvI8XcfVD3h5ljKZRmakRZcNQ1/EbHZVjgEvFB9kZRv4Xf3bCvQJXD4skKAkHsYDDbPS0b9L53jqUx9f/W9O8Gw1kix/PLBZpkeXw+u03zbiqwhPJY0nkO/LWgLEUtKG67zWH1KK6M2bWhq7z0NFMWHaE58WhFlCwmTJA8KUKB+RiHG3a6UoqjJvzkd4f8AkCC19q0u/nByCnRsoxhmPpUhJAv9Whn3rfvUb/tT7F/Uqu30lS5LU5XbJhiyB//vCGuDV5M8GIgLOnVxBIQVSFIX/e9yipCoIB6gnFUUTtc="
    on:
      branch: master
      tags: false

  # production pypi
  - provider: pypi
    user: gdyuldin
    password:
      secure: "EhjyFBvlANx9Qe2cfu+BhoeA+DtVQhry+7VUkh0AUNOtLD2lXYOeKWWveaSQIeWibHEyCIyRiHVVf0eyxZ7VZFToScHFrGy1ck3k4uo5ZWeyg61dBkpBjb8xb3VFUbjzUmAc8z7RgoAPm2wyuo75/k03ty0lm+wDTZTc91e8ldC5VAsVkeVKA/8iSIr67YASJVm1pL+e5lWLvdgKO6rk5ATAjrzXUgrcG6s4HuukZ9qveVLvs1N1PQs44edWXu7tjKw/9/9iPM+4pyyQuE+z5aRai0CH0EDnH9BKEx7UyglAjIs3nUa4OvGDOWk/4QmUfZDTR0SiJi6SX1+t3dh/5LRLov9LEPDqLkuTm6OdzZcPvXXMwuJMmrHcXgwSGEp5VQvI8XcfVD3h5ljKZRmakRZcNQ1/EbHZVjgEvFB9kZRv4Xf3bCvQJXD4skKAkHsYDDbPS0b9L53jqUx9f/W9O8Gw1kix/PLBZpkeXw+u03zbiqwhPJY0nkO/LWgLEUtKG67zWH1KK6M2bWhq7z0NFMWHaE58WhFlCwmTJA8KUKB+RiHG3a6UoqjJvzkd4f8AkCC19q0u/nByCnRsoxhmPpUhJAv9Whn3rfvUb/tT7F/Uqu30lS5LU5XbJhiyB//vCGuDV5M8GIgLOnVxBIQVSFIX/e9yipCoIB6gnFUUTtc="
    on:
      tags: true

